[
  {
    "image1": "https://i.ibb.co/T0sFFkP/1.jpg",
    "image2": "https://i.ibb.co/sWPfnnP/2.jpg",
    "image3": "https://i.ibb.co/3SC34zq/3.jpg",
    "image4": "https://i.ibb.co/NZ94fxN/4.jpg",
    "price": "150.0",
    "description":
      "This cozy room features a comfortable double bed and a private balcony with a view of the garden. You can Get Two Separate bed For Own",
    "roomName": "Garden View Room",
    "roomSize": "300 sq. ft",
    "setInRoom": "Double bed, balcony, TV, and private bathroom",
    "roomAvailability": "1",
  },
  {
    "image1": "https://i.ibb.co/SQbSmw4/1.jpg",
    "image2": "https://i.ibb.co/c1QfkqT/2.jpg",
    "image3": "https://i.ibb.co/7kmtqtj/3.jpg",
    "image4": "https://i.ibb.co/X3QD9WG/4.jpg",
    "price": "200.0",
    "description":
      "Experience luxury in this spacious suite with a panoramic ocean view and a private jacuzzi.",
    "roomName": "Ocean View Suite",
    "roomSize": "500 sq. ft",
    "setInRoom": "King-size bed, jacuzzi, ocean view, TV, and private bathroom",
    "roomAvailability": "1",
  },
  {
    "image1": "https://i.ibb.co/QCZd002/1.jpg",
    "image2": "https://i.ibb.co/cbSc69B/2.jpg",
    "image3": "https://i.ibb.co/9GjjjRm/3.jpg",
    "image4": "https://i.ibb.co/MCvRtLq/3.jpg",
    "price": "120.0",
    "description":
      "A comfortable room with a view of the city, ideal for business travelers.",
    "roomName": "City View Room",
    "roomSize": "250 sq. ft",
    "setInRoom": "Queen-size bed, city view, work desk, TV, and private bathroom",
    "roomAvailability": "1",
  },
];

//   {
//     image1: "room4_image1.jpg",
//     image2: "room4_image2.jpg",
//     image3: "room4_image3.jpg",
//     image4: "room4_image4.jpg",
//     price: 175.0,
//     description:
//       "A charming room with a vintage decor, perfect for a romantic getaway.",
//     roomName: "Vintage Romance Room",
//     roomSize: "350 sq. ft",
//     setInRoom: "Queen-size bed, vintage decor, TV, and private bathroom",
//     roomAvailability: "Available",
//   },
//   {
//     image1: "room5_image1.jpg",
//     image2: "room5_image2.jpg",
//     image3: "room5_image3.jpg",
//     image4: "room5_image4.jpg",
//     price: 130.0,
//     description:
//       "A family-friendly suite with a separate living area and a view of the pool.",
//     roomName: "Family Suite",
//     roomSize: "450 sq. ft",
//     setInRoom: "King-size bed, sofa, pool view, TV, and private bathroom",
//     roomAvailability: "Available",
//   },
//   {
//     image1: "room6_image1.jpg",
//     image2: "room6_image2.jpg",
//     image3: "room6_image3.jpg",
//     image4: "room6_image4.jpg",
//     price: 160.0,
//     description:
//       "A modern and stylish room with a balcony and a view of the city skyline.",
//     roomName: "City Skyline Room",
//     roomSize: "280 sq. ft",
//     setInRoom: "King-size bed, balcony, city view, TV, and private bathroom",
//     roomAvailability: "Available",
//   },
